### ISSUE TITLE
Wiki documentation

### ISSUE THREAD

**Issue by kf6kjg** [InWorldz/halcyon#11]
I've added several pages to the wiki, providing what I hope is a good foundation.  Please review/edit.

If you would like to see a different structure or additions that you don't have the time to accomplish, let me know: I'll see what I can do.

The installation instructions in particular need attention, I'll be starting that once I actually start attempting to do so myself!

**Comment by ddaeschler** [comment]
Looking good. Let me review in more detail tomorrow.

**Comment by ddaeschler** [comment]
This looks good so far. I'm working on some setup tools now that should make this easier.
