### ISSUE TITLE
Can I compile the source with mono 4.x ?

### ISSUE THREAD

**Issue by BogusCurry** [InWorldz/halcyon#12]
Hi ;)

Can I complile the source with mono 4.x ?

Greetings

Bogus

**Comment by mdickson** [comment]
I've done some recent commits to support that so yes.  If you use the runprebuild.sh it will generate a solution file monodevelop can read.  

You wont be able to run everything at present.  There support for a PhysX wrapper for Linux as of yet.  But compiles will work fine.

**Comment by BogusCurry** [comment]
thanks for the fast answer ;D

**Comment by kf6kjg** [comment]
I'm running it, as far as I'm able to without a physics engine to let it operate, on
```
$ mono -V
Mono JIT compiler version 4.0.3 (Stable 4.0.3.20/d6946b4 Tue Aug  4 09:43:57 UTC 2015)
```

(BTW, when your question is answered to your satisfaction it's polite to close the issue. :) )
