### ISSUE TITLE
Get rid of insane overloads on SimChat

### ISSUE THREAD

**Issue by ddaeschler** [InWorldz/halcyon#145]
Inside Scene.PacketHandlers.cs, there are an insane number of confusing overloads on the SimChat function. These have already caused a regression and are prone to cause more coding errors especially if the method signatures need to change again in the future.

I propose that only the first SimChat method that takes all of the parameters be left in place and any parameters that now completed as part of the overloads be left as optional parameters with sane defaults.

**Comment by ddaeschler** [comment]
Full path to the file is OpenSim\Region\Framework\Scenes

**Comment by ddaeschler** [comment]
No takers for this? Definitely a more simple way to get your feet wet in the code

**Comment by MatthewBeardmore** [comment]
Pull request #191

**Comment by jimtarber** [comment]
These changes were included as part of the 0.9.23 release. ;)
