### ISSUE TITLE
Voice not working in InWorldz V3 RC

### ISSUE THREAD

**Issue by ddaeschler** [InWorldz/halcyon#16]
Conversation with Cinder follows:

Cinder: const U64 REGION_FLAGS_ALLOW_VOICE = (1 << 28);
Cinder: there's a region flag and a parcel flag, both need to be active for that button to light up, as well as being connected to vivox, but that isn't the issue.
Cinder: ok, it's the allow voice region flag that's missing for sure.
Cinder: not missing, just off i guess.

**Comment by jimtarber** [comment]
There's code to set it, from the EstateSettings, but I'll do a quick debug trace and see if it's not being persisted or there is an order of access problem, something like that. The EstateSettings have had a bit of a bootstrap ordering issue at startup, which I think is corrected now, but it may still affect the Vivox initialization.

**Comment by jimtarber** [comment]
These issues, and a couple of others, are fixed in pull request #18
