### ISSUE TITLE
hc-database schema

### ISSUE THREAD

**Issue by mjheilmann** [InWorldz/halcyon#164]
When using hc-database.exe I can designate that my table is not named inworldz by using the -s flag.  However, the queries for creating the triggers appear to be hard-coded to the database name inworldz, at least when running --init.

When using -s halcyon, I see the following:

<pre>
Unable to load CORE schema: Error TRIGGER command denied to user 'redacted'@'redacted' for table 'economy_transaction'
While executing query 
/*!50003 CREATE*/ /*!50003 TRIGGER `inworldz`.`upd_total_on_new_trans`
AFTER INSERT ON `inworldz`.`economy_transaction`
FOR EACH ROW
BEGIN
  IF (SELECT COUNT(*) FROM economy_totals WHERE user_id = NEW.destAvatarId) = 0 THEN
		INSERT IGNORE INTO economy_totals SELECT NEW.destAvatarId, SUM(transactionAmount) FROM economy_transaction WHERE destAvatarID = NEW.destAvatarId;
  ELSE
		UPDATE economy_totals SET total = total + NEW.transactionAmount WHERE user_id = NEW.destAvatarId;
  END IF;
END */

Context:

/*!50003 SET sql_mode              = '' */ 

/*!50003 CREATE*/ /*!50003 TRIGGER `inworldz`.`upd_total_on_new_trans`
AFTER INSERT ON `inworldz`.`economy_transaction`
FOR EACH ROW
BEGIN
  IF (SELECT COUNT(*) FROM economy_totals WHERE user_id = NEW.destAvatarId) = 0 THEN
		INSERT IGNORE INTO economy_totals SELECT NEW.destAvatarId, SUM(transactionAmount) FROM economy_transaction WHERE destAvatarID = NEW.destAvatarId;
  ELSE
		UPDATE economy_totals SET total = total + NEW.transactionAmount WHERE user_id = NEW.destAvatarId;
  END IF;
END */
;
/*!50003 SET sql_mode              = @saved_sql_mode */ 
</pre>

There is no database inworldz, and the tables are created under halcyon correctly.

**Comment by ddaeschler** [comment]
This is fixed in https://github.com/InWorldz/halcyon/pull/187
