### ISSUE TITLE
Unknown column 'Materials' in 'field list' exception in MySQLDataStore

### ISSUE THREAD

**Issue by SMondesire** [InWorldz/halcyon#185]
OpenSim.Data.MySQL.MySQLDataStore.ExecuteNonQuery(MysqlCommand c): Throws an exception when performing c.ExecuteNonQuery();

Error: Additional information: Unknown column 'Materials' in 'field list'

Reproduction steps: Loaded an oar (seanston.oar linked below) and the exception occurred. Deleted the region and created a new one. The exception continued to occur. Added Materials column to primshapes, exception does not occur any longer.

seanston.oar: https://drive.google.com/open?id=0Bz23IMCDYq0NZVl4ckJ5VmtLb28

Solution: Added Materials column to primshapes table in Inworldz database.

Query: "INSERT INTO primshapes (UUID, Shape, ScaleX, ScaleY, ScaleZ, PCode, PathBegin, PathEnd, PathScaleX, PathScaleY, PathShearX, PathShearY, PathSkew, PathCurve, PathRadiusOffset, PathRevolutions, PathTaperX, PathTaperY, PathTwist, PathTwistBegin, ProfileBegin, ProfileEnd, ProfileCurve, ProfileHollow, Texture, ExtraParams, Media, Materials, State, PhysicsData, PreferredPhysicsShape, VertexCount, HighLODBytes, MidLODBytes, LowLODBytes, LowestLODBytes) values  (?UUID0, ?Shape0, ?ScaleX0, ?ScaleY0, ?ScaleZ0, ?PCode0, ?PathBegin0, ?PathEnd0, ?PathScaleX0, ?PathScaleY0, ?PathShearX0, ?PathShearY0, ?PathSkew0, ?PathCurve0, ?PathRadiusOffset0, ?PathRevolutions0, ?PathTaperX0, ?PathTaperY0, ?PathTwist0, ?PathTwistBegin0, ?ProfileBegin0, ?ProfileEnd0, ?ProfileCurve0, ?ProfileHollow0, ?Texture0, ?ExtraParams0, ?Media0, ?Materials0, ?State0, ?PhysicsData0, ?PreferredPhysicsShape0, ?VertexCount0, ?HighLODBytes0, ?MidLODBytes0, ?LowLODBytes0, ?LowestLODBytes0),(?UUID1, ?Shape1, ?ScaleX1, ?ScaleY1, ?ScaleZ1, ?PCode1, ?PathBegin1, ?PathEnd1, ?PathScaleX1, ?PathScaleY1, ?PathShearX1, ?PathShearY1, ?PathSkew1, ?PathCurve1, ?PathRadiusOffset1, ?PathRevolutions1, ?PathTaperX1, ?PathTaperY1, ?PathTwist1, ?PathTwistBegin1, ?ProfileBegin1, ?ProfileEnd1, ?ProfileCurve1, ?ProfileHollow1, ?Texture1, ?ExtraParams1, ?Media1, ?Materials1, ?State1, ?PhysicsData1, ?PreferredPhysicsShape1, ?VertexCount1, ?HighLODBytes1, ?MidLODBytes1, ?LowLODBytes1, ?LowestLODBytes1) ON DUPLICATE KEY UPDATE UUID=VALUES(UUID), Shape=VALUES(Shape), ScaleX=VALUES(ScaleX), ScaleY=VALUES(ScaleY), ScaleZ=VALUES(ScaleZ), PCode=VALUES(PCode), PathBegin=VALUES(PathBegin), PathEnd=VALUES(PathEnd), PathScaleX=VALUES(PathScaleX), PathScaleY=VALUES(PathScaleY), PathShearX=VALUES(PathShearX), PathShearY=VALUES(PathShearY), PathSkew=VALUES(PathSkew), PathCurve=VALUES(PathCurve), PathRadiusOffset=VALUES(PathRadiusOffset), PathRevolutions=VALUES(PathRevolutions), PathTaperX=VALUES(PathTaperX), PathTaperY=VALUES(PathTaperY), PathTwist=VALUES(PathTwist), PathTwistBegin=VALUES(PathTwistBegin), ProfileBegin=VALUES(ProfileBegin), ProfileEnd=VALUES(ProfileEnd), ProfileCurve=VALUES(ProfileCurve), ProfileHollow=VALUES(ProfileHollow), Texture=VALUES(Texture), ExtraParams=VALUES(ExtraParams), Media=VALUES(Media), Materials=VALUES(Materials), State=VALUES(State), PhysicsData=VALUES(PhysicsData), PreferredPhysicsShape=VALUES(PreferredPhysicsShape), VertexCount=VALUES(VertexCount), HighLODBytes=VALUES(HighLODBytes), MidLODBytes=VALUES(MidLODBytes), LowLODBytes=VALUES(LowLODBytes), LowestLODBytes=VALUES(LowestLODBytes);"

**Comment by mdickson** [comment]
Hi Sean,

  Yeah the Materials field was added to the *.sql file used to initialize a database but if you had set up your instance prior to the release of that change you wouldn't have it. I'd like to do some work to add schema migration (using Fluent.Migrator) to handle table updates like that in the future.  Sorry you were affected by this in absence of a migration mechanism being in place.

**Comment by SMondesire** [comment]
Thanks Mike for the response. I downloaded the source last week and checked if there were any updates I missed, especially in inworld-core-base.sql and inworldz-rdb-base.sql, but there were none. In those files, the primshapes table does not contain a "Materials" column, although I see "Material" (no 's') in prims.

**Comment by jimtarber** [comment]
We've been adding the column with this:
`ALTER TABLE primshapes ADD Materials longblob AFTER Media;`
Just in case the order matters (it doesn't seem to in our code but it might at some point, e.g. export/import).

**Comment by mdickson** [comment]
Looks like something got lost in a merge. So yes you'll need to manually do the ALTER command Jim mentioned. I may look at Fluent sooner rather than later so we don't lose changes like this and we have a standard way to apply them.

**Comment by SMondesire** [comment]
In OpenSim.Data.MySQL.MySQLDataStore.BuildShape(IDataReader row) there is a cast exception related to the Materials column of type longblob. The query returns a long when the code expects an array. To resolve this issue, I modified  the materials declaration to cast row["materials"] to a byte array of one byte (converting the long to a byte and storing that byte into the materials array). I am not sure if this has any negative consequences but it seems to resolve the issue. Below is the code:

if (!(row["Materials"] is System.DBNull))
            {
                byte[] materials = { (byte)row["Materials"] };
                s.RenderMaterials = RenderMaterials.FromBytes(materials, 0);
            }

**Comment by mdickson** [comment]
Something doesnt seem right here.  The longblob value should come back as a byte array not as a long value.  Are you sure the field is created correctly in your database?  It should be a longblob because its a serialized stream of bytes from all the materials data thats present.

**Comment by SMondesire** [comment]
I originally set Materials to long based on what was written to the db and got the exception. I updated the column to longblob based on Jim's recommendation and reverted the declaration to a byte array. I have not encountered the exception with the datatype change. Thanks for the clarification.
