### ISSUE TITLE
Wiki installation instructions

### ISSUE THREAD

**Issue by cb-dtf** [InWorldz/halcyon#237]
The current installation instructions is close to non-existent, it may slow down or stop potential developers from contributing or using halcyon in the first place.

I have during the installation process created documentation on how to do this, since my setup is not completely running yet, the documentation is subject to change (otherwise I would post it here)

I wish for someone to grant me access to insert/update a wiki page on the installation process.
Please, could any of you give me this access? @kf6kjg @zauberparacelsus @MatthewBeardmore @CmdrCupcake @cinderblocks 

I reached out to @jimtarber via twitter to hear him out if I had any changes, since he has done most contribution, so code wise I have done a fork with the main reason to improve the setup procedure. (done one small enhancement so far)

I'm new to github, since I usually use subversion.

**Comment by mdickson** [comment]
Probably the best way to do this is to checkout and make changes (in your case to the doc directory) adding your new material.  When you have it so you are happy with it then do a pull request so your changes can get reviewed and pulled into the main tree.  

If you definitely want to update the github wiki page then @ddaeschler  is the project owner. He can best address this.

**Comment by cb-dtf** [comment]
Thanks for the guidance @mdickson I will do as you suggested so the content may be reviewed first,
although in the long run, I may have more content and in that case, wiki access would ease the process for me.

That said, it is understandably that you want to review this first set of changes, for evaluation purposes.

**Comment by mdickson** [comment]
So just to be clear, David is the person to address this to. I was just trying to describe the normal workflow for changes to the project.  Changes->PR->Review and Merge.  For the Wiki David may use a different approach including a more open process.  Regardless, I know any contribution is greatly appreciated. Glad you're working with Halcyon!

**Comment by cb-dtf** [comment]
Yep, I understand the workflow now, thanks for the help describing it, I just have to get used to the github ropes now :) 
I am happy to contribute with whatever knowledge I can, its a complex project setup tough, so will be conservative about not breaking anything.

David / @ddaeschler do you have any comments till now? My setup is running now, so it will not be long before I have something to share.

**Comment by ddaeschler** [comment]
The way things are set, anyone should be able to edit the wiki as far as I can tell as I don't have restrictions. Please feel free to add your contributions. We really appreciate the time used to update documentation as we don't get enough of it.

**Comment by cb-dtf** [comment]
Thanks 

I will update the wiki within the next few days.

I thought that it said I needed permissions last time I checked the wiki, but apparently I am wrong, since now I can edit and insert new pages.

Writing documentation part is always the boring part (personal opinion), although since I do it anyway, it might as well be of some use for others as well.
