### ISSUE TITLE
Animation state incorrect when logging in while falling

### ISSUE THREAD

**Issue by kf6kjg** [InWorldz/halcyon#250]
Another interesting SL/Halcyon animation state mismatch: TP to a great altitude, say 4040.  Let your avatar fall, but log out long 'ere you reach ground or any objects.  Some time later, log in again and note your avatar's animation while your altimeter continues to unwind.
SL: falling with flailing limbs (assuming no AO).
IW: standing still.

**Comment by jimtarber** [comment]
I think the trigger on login that starts anims is the first avatar movement update, so if you just login and don't move the avatar, it may just stand and stand regardless.  But take one step and it's fine. So it sounds like something that happens in the AgentUpdate is missing from the initial data send.

**Comment by kf6kjg** [comment]
This issue was moved to HalcyonGrid/halcyon#10
