### ISSUE TITLE
ROW_FORMAT=FIXED on line 1213 in inworldz-core-base.sql causes hc-database.exe to fail to create mysql db.

### ISSUE THREAD

**Issue by sonjamichelle** [InWorldz/halcyon#267]
The text "ROW_FORMAT=FIXED" on line 1213 in ithe file nworldz-core-base.sql causes hc-database.exe to fail to finish creating the database on MySQL 5.7.9 (Windows) and later. Not all the required tables are created.

Halcyon.exe will still run however when the initial region is created and you get to the point where you enter the Master Avatar the server terminates with the error table inworldz.users does not exist.

Subsequent runs of halcyon.exe produce the above error and the error table inwordz.regionsettings does not exist and terminates.

Removing ROW_FORMAT=FIXED solves the issue and allows hc-database.exe to create the full MySQL database and halcyon.exe runs as expected.

**Comment by jimtarber** [comment]
Looks like support for this was removed in 5.7.8 from InnoDB  storage:
https://bugs.mysql.com/bug.php?id=77625

It also looks like OpenSim ran into this issue and just removed the ROW_FORMAT option (set it to default):
http://opensimulator.org/mantis/view.php?id=7799

I don't think it's actually really used here and can be removed from that .sql file, but I @ddaeschler should probably confirm that it wasn't intentionally specified.

**Comment by ddaeschler** [comment]
The option only matters for ISAM and seems like a legacy setting. Probably a premature optimization. I definitely support removing it. Anyone want an easy PR?

**Comment by jimtarber** [comment]
https://github.com/InWorldz/halcyon/pull/278

I've removed the problematic ROW_FORMAT=FIXED, but also added a second commit with the ROW_FORMAT=DYNAMIC removed as well, since that is the default since MySQL 5.7.9, to avoid similar cases like this in the future.

**Comment by sonjamichelle** [comment]
I see this was merged into the code on 9/22 so I assume we can close this issue now?

**Comment by ddaeschler** [comment]
Yes, thank you again!
