### ISSUE TITLE
Default wearables and Library items not accessible due to owner check

### ISSUE THREAD

**Issue by appurist** [InWorldz/halcyon#287]
We have a problem in the Halcyon code in that the default avatars are broken, and I believe that is because the outfit includes inventory items that are in the (shared) Library.  I think the root problem is the owner check in the inventory code, which is necessary for security reasons, but it prevents an outfit from having items in the Library or being any specific item ID (like a constant).

Second Life solves the Library problem by _copying_ any Library items to the user's inventory when they are added to an avatar.  I'm not sure if it just provides a new item ID  or other details, but it is very visible in Second Life as it copies a whole outfit folder to the user inventory when it is worn from the Library.

In this case though, it's actually the _default_ avatar wearables, not the Library (see image below), so it may be possible to just use a list of exceptions, a whitelist for "built-in" itemIDs that skip the inventory owner check.
![Default outfit](https://i.gyazo.com/76c4b655b5e89fe8b616046602276cc2.png)
![Default wearables](https://i.gyazo.com/22c292e8c8293d8c109169160d386914.png)
I'm not sure of the specific here yet (in the problem or any possible solutions) but I wanted to document the problem so that everyone is aware.

**Comment by kf6kjg** [comment]
This issue was moved to HalcyonGrid/halcyon#8
