### ISSUE TITLE
Economy Module

### ISSUE THREAD

**Issue by sonjamichelle** [InWorldz/halcyon#311]
Now that I've opened my big mouth and have said everything is up and running smoothly, the boss (my wife) wants to implement a working economy module. I've had no luck researching the various "modules" out there as far as they would relate to Halcyon. (Hell, even the OpenSim stuff was rather pitiful) I know a working economy is possible, InWorldz is doing it. We have a working LandTool.php (or rather a LandTool.aspx) that allows us to sell and buy land. In the DB I can set avatar's balances and avatars can exchange funds. But of course there is no automation to any of this.

**Comment by ddaeschler** [comment]
Sorry for the delay. I'm not sure why I'm not getting notices for issue updates here, but I plan to correct that.

As you've noticed, Halcyon does have a working money module, but you're missing the external parts to add funds to accounts. Right now, we do this through the website for I'z purchases which inserts the proper rows into the economy database. The table is a pretty simple ledger format, but it is undocumented. What functionality are you looking for? Maybe we can find a way to get a more simple interface written

**Comment by sonjamichelle** [comment]
We're looking at our users being able to visit a secure page on the website where they can enter the amount of our currency they want to purchase. That transaction would be handled by PayPal. Once cleared the amount they purchased would be added to the economy_totals table in the database. With these funds they would be able to purchase land, goods and services from other residents. We'd also like to set up a monthly/weekly stipend system as well for paid "VIP" members.

**Comment by sonjamichelle** [comment]
Working on our economy and I'm running into an issue. When I pay an avatar the funds don't subtract from my total or add to the other avatar's total. In the DB the transaction registers in the table economy_transaction, but economy_totals is unaffected. Thanks to @vinhold we're making progress on our economy setup. But until I can figure out what's up with the economy_totals table this issue really brings things to a halt.

**Comment by zauberparacelsus** [comment]
Are the avatars involved located on different regions?  There is a known issue where if somebody else pays you while on another region, the viewer's balance will not adjust until something else causes your balance to update (such as clicking your balance or receiving payment from someone on the same region)

**Comment by sonjamichelle** [comment]
Nope, happens even when the avatars are standing right next to each other.

**Comment by zauberparacelsus** [comment]
Okay, I actually misread your prior post anyways.  I've got a cold right now, so my head isn't quite screwed on correctly :-/

**Comment by sonjamichelle** [comment]
I feel ya, I'm in the same boat. slept almost 20 some hours to get to a semi-functional state.

**Comment by appurist** [comment]
The value in `economy_totals` is just a cached value to avoid having to calculate the actual balance.  It is optional. InWorldz did not add that table for many years.  Transactions do not create any entries there; that entry is created when a viewer requests the current balance (typically done at login time).  You may be able to force a refresh (depending on the viewer) by clicking on the balance at the top of the viewer screen.  Or just relog.

See AvatarCurrency.cs for that code, [here](https://github.com/InWorldz/halcyon/blob/master/OpenSim/Region/CoreModules/Avatar/Currency/AvatarCurrency.cs#L379).

**Comment by ddaeschler** [comment]
There is a trigger in the database for all transactions that updates the balance.

https://github.com/InWorldz/halcyon/blob/master/bin/inworldz-core-base.sql#L358

**Comment by appurist** [comment]
Oh good point.  If it's missing, it's also summed and the new record _created_ by the getCurrentBalance() implementation, but I mistakenly thought that the issue was that the `economy_totals` entry for the user was not getting created here at all here.
Rereading, the report said "unaffected", so presumably that means already _existing_ in the table (but not getting updated).  In that case, it's clearly the trigger @ddaeschler mentioned above is not present on your db. Give that a try!

**Comment by sonjamichelle** [comment]
Ok bear with me, SQL is not my strong point. how would I go about checking for that trigger in my DB and how would I go about adding it if it is not?

**Comment by appurist** [comment]
I haven't written triggers either, but they are bits of stored MySQL code that run when another event happens. In this case, the event is an `INSERT` happening on `economy_transaction`.  And in this case, it's an `AFTER` trigger, so any time a record is inserted to `economy_transaction`, _after_ it completes successfully, this stored SQL code will run.  I believe it's delimited with ;; because there's a ; inside the `BEGIN` `END`.  

So I believe it's just the code @ddaeschler linked to above, without the comments... I think if you paste this into MySQL WB and run it, you should be fine:
```
DELIMITER ;;
CREATE TRIGGER `upd_total_on_new_trans`
AFTER INSERT ON `economy_transaction`
FOR EACH ROW
BEGIN
  IF (SELECT COUNT(*) FROM economy_totals WHERE user_id = NEW.destAvatarId) = 0 THEN
		INSERT IGNORE INTO economy_totals SELECT NEW.destAvatarId, SUM(transactionAmount) FROM economy_transaction WHERE destAvatarID = NEW.destAvatarId;
  ELSE
		UPDATE economy_totals SET total = total + NEW.transactionAmount WHERE user_id = NEW.destAvatarId;
  END IF;
END ;;
```

**Comment by sonjamichelle** [comment]
@vinhold to the rescue: He's been replying to me in email with several issues we've been working on.

> 
> This is the DB Trigger. Run this in the MySQL Workbench for the database:
> 
> -- Trigger creation for economy processing. May require setting up a Routine process to make it.
> 
> ```
> DELIMITER $$
> CREATE DEFINER=`root`@`localhost` TRIGGER `mydata`.`upd_total_on_new_trans`
> AFTER INSERT ON `mydata`.`economy_transaction` -- This line shows as a syntax error.
> FOR EACH ROW
> BEGIN
>   IF (SELECT COUNT(*) FROM economy_totals WHERE user_id = NEW.destAvatarId) = 0 THEN
>   INSERT IGNORE INTO economy_totals SELECT NEW.destAvatarId, SUM(transactionAmount) FROM economy_transaction WHERE destAvatarID = NEW.destAvatarId;
>   ELSE
>   UPDATE economy_totals SET total = total + NEW.transactionAmount WHERE user_id = NEW.destAvatarId;
>   END IF;
> END$$
> DELIMITER ;
> ```
>  
> Bob Curtice

Got it working now. Avatars are paying each other. Complete with the Kaching sound. ;-)

**Comment by Vinhold** [comment]
Note that the trigger mentioned above by Sonja, came from the DB Schema for the MySQL DB I got from David when I set up my grid. I have maintained it for all changes added to the DB since. :)

**Comment by appurist** [comment]
Looks like we can close this one now?

**Comment by sonjamichelle** [comment]
Not quite yet, still ironing out some kinks.  ;-)

**Comment by sonjamichelle** [comment]
Closing this issue for now. We've got a working system in the works, thanks to @Vinhold. The finished version will be released for public consumption some time in the future.
