### ISSUE TITLE
Under MySQL folder version numbers are not always incremented upon change.

### ISSUE THREAD

**Issue by kf6kjg** [InWorldz/halcyon#34]
I'm not really certain what the version numbers are for, but I did notice that he Cassandra code made sure to increment them after every change.  The MySQL code only does so sporadically.

What issues can this cause?

**Comment by ddaeschler** [comment]
This can cause the viewer to see an older version of a folder on login when one of those changes happen. The viewer wont bother to download a folder with a version number it already has cached.
