### ISSUE TITLE
Support Linux Compatibility (e.g. compatible with Ubuntu 14 / 64 bits)

### ISSUE THREAD

**Issue by johnfelipe** [InWorldz/halcyon#383]

**Comment by kf6kjg** [comment]
I have run all the Halcyon servers under Mono many times on both 14.04 64, and on 16.04 64. There is a caveat: only BasicPhysics works at this time.

**Comment by johnfelipe** [comment]
Bro do u have cheatsheet for install with robust env?

**Comment by mdickson** [comment]
Just to be clear, Running on Linux is pretty much a dev only configuration.  You wouldn't want to use it to host real regions.

**Comment by kf6kjg** [comment]
What do you mean by "robust env"? Please write clearly.

**Comment by johnfelipe** [comment]
Why is not possible run in production environment?

**Comment by johnfelipe** [comment]
Grid and robust.exe

**Comment by kf6kjg** [comment]
Halcyon does not use ROBUST and is incompatible with any OpenSim systems.

**Comment by johnfelipe** [comment]
The grid is standalone?

**Comment by mdickson** [comment]
You wouldn't want to use it in production because it effectively doesn't have physics.  The Basic Physics that Ricky mentioned is just enough to get a region to load.  

There's no Robust.exe because the Halcyon codebase was forked before the Robust work was done in OpenSim.  It's a single ini file rather than the multiple level configs in Robust.

**Comment by kf6kjg** [comment]
You can configure for standalone or you can configure for grid mode and launch each of the servers, either on one machine, across multiple VMs, or across multiple machines:
* MySQL Database
* WHIP server
* User Server `mono OpenSim.Grid.UserServer.exe`
* Grid Server `mono OpenSim.Grid.GridServer.exe`
* Messaging Server `mono OpenSim.Grid.MessagingServer.exe`

And then as many configured single-region-per-process region servers: `mono Halcyon.exe`.  To be clear, Halcyon only supports having ONE REGION for every instance of Halcyon.exe.

**Comment by appurist** [comment]
Quick resummary: the main problem with running under Linux at this time is the lack of PhyssX.NET support for physics. I believe this is being worked on but there is no expected date yet.  

Some initial configuration tips are [here](https://github.com/InWorldz/halcyon/wiki/Configuration). While Halcyon generally supports a single INI file, Ricky has enhanced it to allow a common INI file and per-region overrides, as described in that Wiki page.  Most of the `Halcyon.ini` file is common across all regions.  It's not particularly clear from that wiki page how to use that though. Ricky @kf6kjg perhaps that could be clarified? e.g. It doesn't say where to put the common INI file (or what it is called) and where to put the per-region overrides (or what it is called). The only name given is `Region1.ini` which I am guessing is not a literal filename.

**Comment by kf6kjg** [comment]
@appurist, Actually that multifile support was already built in, all I did was trace the code to discover it.  I'll poke Vin about that page, it's something he's been working on.

**Comment by Vinhold** [comment]
Thank you Appurist, I will work on making the Halcyon Wiki Configuration a bit more clear. The Region override files was an example name. As in a pattern region1.ini, region2.ini etc. It can even just be Region.ini since there is only one copy in the region folder and that makes even easier for multiple region instance duplication. I have been learning a lot more about how to do this in the last couple of weeks.
I am also working on more detailed configuration options for Halcyon setup to be added later this week after I have proven some of them in the IMA grid setup.

**Comment by appurist** [comment]
@Vinhold That's still a bit ambiguous. Are you saying it will match _any_ `*.ini` file and load it? Or `region*.ini`?  In the same folder as the `halcyon.exe` file, or only in the _current_ directory (so you might `cd` into the subfolder and run `../halcyon.ini`) ?

**Comment by johnfelipe** [comment]
May be a cheatsheet with all steps, path, editions

**Comment by Vinhold** [comment]
Editing the page now, just saved the portion on the region.ini. In practice I found it to be a lot simpler to have the region.ini override file remain named just like that and the batch file point to  --inifile=Region.ini makes it easier when making copies of the desktop icons and only edit the start in folder name.

**Comment by Vinhold** [comment]
@johnfelipe: The documentation is a work in progress. Lol I am adding to it as we are discussing this thread now. But a lot more needs to be put in. Like the full list of Halcyon command line parameters, then which of those lead to later maintenance headaches vs. which practices makes life much easier. I have just been there and done that in doing several grid setup and installations! :)

**Comment by kf6kjg** [comment]
@johnfelipe Vinhold's working on the page with how to do a full grid setup, but I'm afraid there's currently no cheatsheet.

**Comment by kf6kjg** [comment]
As this is more of a meta issue than a single task I'm closing.  Be assured that it's the primary goal of the [first major milestone](https://github.com/InWorldz/halcyon/milestone/1) to get to fully supporting Linux based simulators.
