### ISSUE TITLE
Grid Services Command Line Parameters

### ISSUE THREAD

**Issue by Vinhold** [InWorldz/halcyon#384]
I just checked with Ricky on this one. The User, Grid,  and Messaging services are hard coded for reading Halcyon.ini from the local folder. It looks like a simple "copy the code block" from Halcyon.exe and put in for the each of the services where they read the Halcyon.ini.  This will allow the services to also read from a common configuration source for the Master Halcyon.ini as well as an instance override Halcyon.ini source as it is available for the Halcyon.exe.

Optional wish is to have each one's config data to be also URL or Path location. This would greatly help in management of multiple instances of these services.

**Comment by appurist** [comment]
Hmm, I think the changes to use a two-level hierarchy of ini files were done and released some time ago. Is this Issue completely resolved now?

**Comment by Vinhold** [comment]
I am not sure that the Grid services actually allow a command line option to open Halcyon.ini from someplace other than the local folder. If that can be done now, this is no longer an issue.

**Comment by appurist** [comment]
There are two options, one for `--inifile` and one for `--inimaster` as well as `--inifolder` for specifying the folder and you can see the full list [here](https://github.com/InWorldz/halcyon/blob/master/InWorldz/Halcyon/Application.cs#L121).

InWorldz doesn't use them so If there is any problem with those we may not be aware. Let me know if they don't "just work".  You can also specify any of those in the `[Startup]` section of the `Halcyon.ini` file, although I'm not clear how the catch-22 in doing so would work. ;) (I think if the Halcyon.ini file specified different startup locations, it would affect where options were read from _thereafter_.)

The handling of these options can be seen [here](https://github.com/InWorldz/halcyon/blob/master/OpenSim/Base/ConfigurationLoader.cs#L81).

**Comment by kf6kjg** [comment]
Actually what Vin's talking about is in places like the [User Server's Main Class](https://github.com/InWorldz/halcyon/blob/master/OpenSim/Grid/UserServer/Main.cs#L181) where only the single local Halcyon.ini is loaded.  This differs from what the region does.  I've not yet had the time to fix it.

**Comment by appurist** [comment]
Oh, this refers to the central grid services, rather than region servers.  Yeah, the startup code is different there.

**Comment by kf6kjg** [comment]
This issue was moved to HalcyonGrid/halcyon#6
