### ISSUE TITLE
Sucessful build but no Halcyon.ini.example?

### ISSUE THREAD

**Issue by kf6kjg** [InWorldz/halcyon#4]
Good job on getting the server code up!  It even compiled out of the gate after executing `./runprebuild.sh` and opening the solution in monodevelop.

However the ini file example is missing from the codebase, so I can't boot up the server to give it a test run.  I'll see if I can sneak one from a friend who's got a working grid.

Or if there's something else I need to do, let me know - I'm already contemplating what needs to be written for documentation! :D

**Comment by jimtarber** [comment]
The code is currently committed but there are a lot of details remaining that are needed before a Halcyon server will start up. Database schemas and configuration files at the top of the list.  It's coming, and we're also working on a simplified installation, like a Halcyon-on-a-stick or -in-a-box.  Hope to have the config stuff all committed this week.  

Also, once that is done, you'll also need another patch to start on Linux.  Currently Halcyon relies on PhysX.NET and there's no equivalent PhysX wrapper for Linux (yet).

**Comment by kf6kjg** [comment]
After a whirlwind of research stemming from your response I see that MOSES team is working on PhysX.NET for OS, though the Linux compatibility seemed to be in the air there too - could have been out-of date info.

I also saw that nVidia open-sourced the CPU implementation of PhysX earlier this year! Boy I'm behind on my news...

WRT to the stick/box idea, that's great!  If I may suggest, I'd start by choosing a good hypervisor and releasing images/"virtual appliances" for it.  I'm currently partial to VirtualBox, but that's simply because I got tired of hacking VMDKs to make my own VMs for VMWare Player...

Keep up the good work!

**Comment by ddaeschler** [comment]
You can find the halcyon ini sample at Halcyon.sample.ini in /bin. If this is the Ricky I think it is, you're already running a private grid on inworldz code, so you should have the database schema on hand.

**Comment by kf6kjg** [comment]
This is the Ricky you're thinking of!  Good to hear from you David.  cough.. anaximander... cough... :P

Ah found it.  So... which is correct, the filename or the code?  The error the server reports is:
```
17:56:39 - [CONFIG] Reading configuration settings
17:56:39 - [CONFIG] Could not load any configuration
17:56:39 - [CONFIG] Tried to load /home/ricky/development/inworldz/halcyon/bin/Halcyon.ini, 
17:56:39 - [CONFIG] and XML source /home/ricky/development/inworldz/halcyon/bin/Halcyon.xml
17:56:39 - [CONFIG] Did you copy the ./Halcyon.ini.example file to ./Halcyon.ini?
```

Hence that's the file I was looking for.

**Comment by ddaeschler** [comment]
Yeah, you should just be able to rename Halcyon.sample.ini to Halcyon.ini and fill out the changes.

**Comment by ddaeschler** [comment]
I'm going to fix the help text. It's wrong.

**Comment by kf6kjg** [comment]
Looking at the code in ConfigationLoader.cs:140 this could be an exercise.  It's written assuming the appending of the sample extension, not the insertion of it.  Might be easier just to reverse the filename change - though that forfeits highlighting in the example/sample file...

**Comment by ddaeschler** [comment]
All fixed. I kept the name of the file as it was and fixed the handler.

**Comment by kf6kjg** [comment]
Nice one.
