### ISSUE TITLE
Possible MySQL bug adding/updating a region on the grid server.

### ISSUE THREAD

**Issue by kf6kjg** [InWorldz/halcyon#42]
As I've been exploring the code, especially as regards the MySQL information, it seems that there's a lot of old dead code - however I'm never 100% certain that any one piece is actually dead...

One of them is what appears to be [an SQL bug in assigning the owner's UUID to a region](https://github.com/InWorldz/halcyon/blob/master/OpenSim/Data/MySQL/MySQLGridData.cs#L412). Look near the end of the line for `owner_uuid - ?owner_uuid`.  However, I think this may be dead code that's never called - I'm pretty sure you guys would have migrated this off, but I can't find where it might have gone to... Unless you only migrated inventory to Cassandra and left the region stuff in MySQL?

**Comment by ddaeschler** [comment]
It's dead code. At the top of the function is:

bool GRID_ONLY_UPDATE_NECESSARY_DATA = false;

It is never assigned to after that

**Comment by kf6kjg** [comment]
Ok. I'll not let it distract me at this time then.  Such dead code should probably be purged, but that takes someone with more knowledge of what's in use and what's not than I currently have - and would be a different issue.  I can track down dependencies, but I get lost at certain levels - plugin layer for one.

In this case I didn't check the source of that conditional, but instead followed the call tree.  Silly me: should have started with the obvious.
