### ISSUE TITLE
Halcyon Texture issues  after we got  it up 

### ISSUE THREAD

**Issue by Ana-Green** [InWorldz/halcyon#422]
After Vin and others  did get it to run the textures on a flat region are  gone, its  just a grey flat region.
See  picture, however if  I  load "oar" a  complete region what's  mainly mesh  based it looks ok, also  I  found another  MySQL issue maybe related  to this  texture  issue or  not.

The user Frank activated by  the  name  region, and  not root  seems not to work anymore as result that the database : dsdata, can  and will  not  start, that's why  region dsg1 -  dsg8  are  also  down at  the  moment, but let us focus just  on this  one welcome region  see log: 
  
[Low physics FPS 43.60465.txt](https://github.com/InWorldz/halcyon/files/1736540/Low.physics.FPS.43.60465.txt)

First pinhead should be green,  its  grey  👎 
![9500avi_001](https://user-images.githubusercontent.com/36156774/36376096-300dd3dc-1572-11e8-96ae-26a403cb2892.png)

Any  ideas?  

With Love Ana

**Comment by Vinhold** [comment]
Problem resolved. I had loaded the Inventory and Assets folder and it had the flag file to not load the inventory in it. So when the regions she created started up, the default Library textures and items were not loaded resulting in no textures. I subsequently removed the file and restarted the region and all was restored.
