### ISSUE TITLE
llParcelMediaQuery() for PARCEL_MEDIA_COMMAND_DESC returns wrong data

### ISSUE THREAD

**Issue by Vinhold** [InWorldz/halcyon#425]
I had not discovered this problem earlier because I simply had no parcel description in Gospel World where I was using my Media Presenter program. That program provides a Power Point style presentation in world using graphics uploaded to the website using FTP services for the users account. 
Problem:
Running this command in a script:
list data = llParcelMediaQuery([PARCEL_MEDIA_COMMAND_DESC]);
will return the parcel description data not the Media Command Description field. Test by putting 
"This is the Parcel Description" in the Parcel description field and "This is Media Description" in the Media description field and see which this command will return. I am getting the Parcel Description back.

**Comment by appurist** [comment]
Good catch, I see the bug and will commit the fix.

**Comment by appurist** [comment]
Looks like a quick easy fix, committed in pull request #426
