### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by WhiteCoreWebUI** [InWorldz/halcyon#430]
After i fixed my scripts issues now the next questions,

1. What is the correct map server url to use? as all viewers besides Firestorm only report a "water" map i can find the regions but the textures wont show up.

2. I see the Regions have the GetTexture CAPS how do i call it from web, over the region itself, aperture or whip?

**Comment by emperorstarfinder** [comment]
Hey there,

You have to run both Whip and Aperture.  Whip is the actual Asset server and Aperture helps speed up texture and mesh rendering.   My team has aperture running on our machines running regions and Whip on our machine running the grid services for our Halcyon test grid.

According to Halcyon.ini the Map Server URI should be: MapImageServerURI="http://xxx.xxx.xxx.xxx:9000/" (Replace the x with your domain url or IP).

In reality, all you should need to do for it to work correctly is leave all the defaults in the configuration files except add the DB connection strings and change the IP addresses to your domain url or IP address.  
Other then that you should be good to go with textures for regions showing up properly in all viewers.

**Comment by WhiteCoreWebUI** [comment]
I have the Defaults set but the map textures only show up properly in firestorm and i am in gridmode so i am not sure the 9000 port is valid in that case

**Comment by emperorstarfinder** [comment]
It would appear to be as it shows up in all viewers for me.  However, in grid mode, you also have to make the necessary changes in a couple of xml configuration files as well.  You can always email me directly and I can pass you a copy of the xml files if you don't have them.

**Comment by WhiteCoreWebUI** [comment]
i have the xml files and grid is running files i am just not sure about UserServer_Config.xml there it says to map_server_uri which by default is empty and defaults to secondlife

**Comment by emperorstarfinder** [comment]
Add the "http://xxx.xxx.xxx.xxx:9000/" there (change the xxx.xxx.xxx.xxx to your domain url or IP address) should sort that out.

**Comment by WhiteCoreWebUI** [comment]
set as advised
no change
![karte](https://user-images.githubusercontent.com/9350749/37470477-e543e14e-2867-11e8-97e7-30bac444f8a0.PNG)

**Comment by emperorstarfinder** [comment]
What viewer are you using?

**Comment by WhiteCoreWebUI** [comment]
Inworldz3 Singularity and Firestorm

**Comment by emperorstarfinder** [comment]
Okay, The InWorldz viewer I am seeing the same thing so that is likely an issue with their specific viewer.

For Firestorm (For OpenSim) you should see something similar to this:

![2018-03-15](https://user-images.githubusercontent.com/2190078/37471204-928e4520-283f-11e8-9a58-dcee365c3a27.png)

**Comment by WhiteCoreWebUI** [comment]
![fire](https://user-images.githubusercontent.com/9350749/37471343-d024a09e-2869-11e8-8e9b-b5f7bc7340da.PNG)
Yes like is said before firestorm is fine

**Comment by emperorstarfinder** [comment]
Yeah, I think its just they need to update their specific viewer (potentially).  For the most part, Firestorm is widely used by many people (on most grids) from what I am aware of at the moment.

**Comment by WhiteCoreWebUI** [comment]
yes but it is still a issue as the same viewer works fine on the inworldz grid, i think they need an update on the wiki on how to set this up

**Comment by emperorstarfinder** [comment]
The info is there on the wiki on the configuration page (though it could be written better).  But your configs are correct now if Firestorm is seeing it correctly so in this case it is likely an issue with their specific viewer.

**Comment by WhiteCoreWebUI** [comment]
yes but for example on inworldz the mapserver uri returns http://places.inworldz.com/map2.php/ in their own viewer, i think inworldz is not picking that up correctly

**Comment by emperorstarfinder** [comment]
Yes but the Halcyon architecture does not have everything that InWorldz does.  In fact they haven't updated the viewer since they open sourced Halcyon (would need to check their last commit).  However their viewer is based on an older version of the Alchemy Viewer.  So you could take the latest Alchemy viewer and that probably will work.

**Comment by WhiteCoreWebUI** [comment]
Alchemy has the same issue, just tested

**Comment by emperorstarfinder** [comment]
Okay then rest assured your configs are correct.  Its likely a bug with how the info is being received by the viewer itself.

**Comment by cinderblocks** [comment]
You could open the viewer logs and see why it isn't downloading the tiles instead of throwing up your arms and saying two out of three viewers are broken.

**Comment by kf6kjg** [comment]
Do you have a map generator and tile server set up? If not, check out
Anaximander 2:

https://github.com/kf6kjg/Anaximander2

That gets the tiles made. Next you need a web server to serve them to the
viewer. For that I still need to translate the Examples folder from Anax1
over to the new repo, but you can find them here:

https://github.com/kf6kjg/Anaximander/tree/master/examples Please note that
I've not yet tried these examples against the new Anax2, they may need work
- most likely simplification.

It's this web server that you need to set in your INI and UserServer's xml.
Running on memory here so YMMV: in bed ill ATM. :/


It looks to me like the viewers are not finding the map server and failing.
FS is doing the same, but falling back to an ancient region protocol that's
been deprecated but not yet excised from Halcyon.

**Comment by kf6kjg** [comment]
Also, the current release version of Anax2 has some bugs since resolved in
the master branch. If you can, please build from source until I get the
next release out.

**Comment by WhiteCoreWebUI** [comment]
this explains a lot i will try it now

**Comment by WhiteCoreWebUI** [comment]
yay it works perfectly thanks a lot this helped

**Comment by WhiteCoreWebUI** [comment]
now only the gettexture for now i solved it by hardcoding the uuid instead of uuid.random but i dont think this is a suitable solution.

**Comment by kf6kjg** [comment]
As stated previously, Aperture is to be responsible for providing textures
to the viewers.

**Comment by WhiteCoreWebUI** [comment]
yes i am fetching it from there and convert it to jpeg but it uses a random uuid for the GetTexture and GetMesh it doesnt seem to have a GetTexture/?texture_id=<uuid> http handler

**Comment by kf6kjg** [comment]
Wait. Are you accessing it from a non viewer codebase? If so is such code
inside your server network? If that's also true, and you are using C#, get
the assets using the Chattel library on NuGet.

The CAPs system, and Aperture, is designed around logged in viewers.

**Comment by WhiteCoreWebUI** [comment]
well this is what i am doing to display profile pictures on my website:
<?php

$uuid = escapeshellcmd(mysql_escape_string($_GET["uuid"]));
$s = 256 | 0;
$geom = $s."x".$s;
$size = escapeshellarg($geom);

$url = "http://domain.com:8000/CAPS/HTT/5f8e7183-97eb-42eb-a0db-2fa668268b63/?texture_id=$uuid";

if (!file_exists("./tmp/$uuid-$geom.png"))
{
	copy ($url, "./tmp/$uuid.j2k");
	exec ("j2k_to_image -i ./tmp/$uuid.j2k -o ./tmp/$uuid.tga");
	exec ("convert -scale $size ./tmp/$uuid.tga ./tmp/$uuid-$geom.png");
	unlink ("./tmp/$uuid.j2k");
	unlink ("./tmp/$uuid.tga");
}

if (!file_exists("./tmp/$uuid-$geom.png"))
{
	exit;
}

header("Content-type: image/png");

$fd = fopen("./tmp/$uuid-$geom.png", "r");
fpassthru($fd);
fclose($fd);

**Comment by WhiteCoreWebUI** [comment]
$uuid = escapeshellcmd(mysql_escape_string($_GET["uuid"]));
$s = 256 | 0;
$geom = $s."x".$s;
$size = escapeshellarg($geom);

$url = "http://domain.com:8000/CAPS/HTT/5f8e7183-97eb-42eb-a0db-2fa668268b63/?texture_id=$uuid";

if (!file_exists("./tmp/$uuid-$geom.png"))
{
	copy ($url, "./tmp/$uuid.j2k");
	exec ("j2k_to_image -i ./tmp/$uuid.j2k -o ./tmp/$uuid.tga");
	exec ("convert -scale $size ./tmp/$uuid.tga ./tmp/$uuid-$geom.png");
	unlink ("./tmp/$uuid.j2k");
	unlink ("./tmp/$uuid.tga");
}

if (!file_exists("./tmp/$uuid-$geom.png"))
{
	exit;
}

header("Content-type: image/png");

$fd = fopen("./tmp/$uuid-$geom.png", "r");
fpassthru($fd);
fclose($fd);

**Comment by WhiteCoreWebUI** [comment]
i am using php so i probably wont come around to writing my own texture handler using chattel as it seems

**Comment by kf6kjg** [comment]
From my perspective your options are limited:
* Connect to WHIP using a custom PHP implementation of a WHIP client - I
know of no existing open source project that has that.
* Build a C# based service using Chattel to provide the textures.
* Have user upload their own "web profile" pictures.
* Have your PHP somehow pretend to be a viewer and get a CAP URL for
textures from a region. That would provide the correct GUID, but I think
will cause a cascade of other problems to solve.

**Comment by WhiteCoreWebUI** [comment]
for now i solved it by modifying halcyon to use one global aperture with a fixed CAP for gettexture (no bugs seen so far)

**Comment by kf6kjg** [comment]
That causes all viewers to use the same cap and will cause problems with
rate limiting and other things. Consider it a very bad hack that should not
survive into a production grid - or a grid that ever has more than one
viewer logged into the whole grid.

**Comment by WhiteCoreWebUI** [comment]
yes i am considering to add a httphandler cap to aperture

**Comment by WhiteCoreWebUI** [comment]
but the global aperture i will probably keep , considering the machine running it is fast enough lol

**Comment by kf6kjg** [comment]
One other way you could go is to have your php tell Aperture to create a
given CAP using the admin API like a region does. Then just use that
resulting CAP. No code mods required to the region or Aperture. And you
don't have to learn to grok WHIP protocol.

**Comment by WhiteCoreWebUI** [comment]
do you have an example to create a cap?

**Comment by kf6kjg** [comment]
See my notes https://github.com/kf6kjg/f-stop/blob/master/apertureAPI.md
I was reverse engineering the protocol from the source in order to write
f-stop.

**Comment by kf6kjg** [comment]
Aperture restricts bandwidth on a per cap basis. Nothing to do with your
server, everything to do with viewer preferences.

**Comment by WhiteCoreWebUI** [comment]
ok i am creating a cap with php now render the image and remove the cap again with php i hope that is the right way to do it.

**Comment by WhiteCoreWebUI** [comment]
```
function GUID()
{
    if (function_exists('com_create_guid') === true)
    {
        return trim(com_create_guid(), '{}');
    }

    return sprintf('%04X%04X-%04X-%04X-%04X-%04X%04X%04X', mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(16384, 20479), mt_rand(32768, 49151), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535));
}    
$guid = GUID();
$response = file_get_contents('http://MYDOMAIN:8000/CAPS/HTT/ADDCAP/MYTOKEN/'.$guid.'/50000');
$uuid = escapeshellcmd(mysql_escape_string($_GET["uuid"]));
$s = 256 | 0;
$geom = $s."x".$s;
$size = escapeshellarg($geom);

$url = "http://MYDOMAIN:8000/CAPS/HTT/$guid/?texture_id=$uuid";

if (!file_exists("./tmp/$uuid-$geom.png"))
{
	copy ($url, "./tmp/$uuid.j2k");
	exec ("j2k_to_image -i ./tmp/$uuid.j2k -o ./tmp/$uuid.tga");
	exec ("convert -scale $size ./tmp/$uuid.tga ./tmp/$uuid-$geom.png");
	unlink ("./tmp/$uuid.j2k");
	unlink ("./tmp/$uuid.tga");
}

if (!file_exists("./tmp/$uuid-$geom.png"))
{
	exit;
}

header("Content-type: image/png");

$fd = fopen("./tmp/$uuid-$geom.png", "r");
fpassthru($fd);
fclose($fd); 
unlink("./tmp/$uuid-$geom.png");
$lol = file_get_contents('http://MYDOMAIN:8000/CAPS/HTT/REMCAP/MYTOKEN/'.$guid.'/');
```

**Comment by kf6kjg** [comment]
From a casual read, just make sure that MYTOKEN is the secure token you set
in Aperture's county config file.

Also, I'd personally keep the cap open for a while and have it serve many
requests, but that takes more work on your part.

**Comment by WhiteCoreWebUI** [comment]
yes i changed my domain and my token so nobody can access my aperture lol

**Comment by WhiteCoreWebUI** [comment]
On a sidenote: Leaving the bw from the Addcap away causes Aperture to crash

**Comment by mdickson** [comment]
How in the world is this related to GetMesh?  All the tooling for that is already in the region server

**Comment by kf6kjg** [comment]
The second issue in the OP was about how to read textures from php. He's
got that almost solved now.

**Comment by mdickson** [comment]
Got it.  Is the mesh handling working now or still broken?

**Comment by kf6kjg** [comment]
Different issue. You're thinking of issue 432.

**Comment by WhiteCoreWebUI** [comment]
@kf6kjg thanks for the idea about keeping the cap open, i now have a bit of balancing in that cycles through 6 aperture servers and writes the cap it openened to the database and a cronjob closes the cap after 2 hours so i am sorted, you can close this issue :)
