### ISSUE TITLE
New LSL Function: iwCheckProfileFlag

### ISSUE THREAD

**Issue by zauberparacelsus** [InWorldz/halcyon#431]
The following is a proposal for a pair of LSL functions, which is similar in scope to iwIsPlusUser, or llRequestAgentData with DATA_PAYINFO.  These functions would be potentially useful for land/region management scripts, as well as any LSL-based grid management scripts.

I have chosen to propose this on the halcyon github rather than the InWorldz mantis, due to applications for non-InWorldz grids based on Halcyon.

`integer iwCheckProfileFlag(key avatar, string flag);`
The function checks to see if the specified avatar's profile flags contains the specified flag, and then returns TRUE if it does, or FALSE if not.  In this context, a "profile flag" includes things such as "Resident", "Cornerstone", "InWorldz Employee", "Payment Info On File" etc.  If a grid is using any custom flags such as "Grid Monkey", "Mentor", or such, the function would be able to check for those as well.

`integer iwCheckProfileFlagList(key avatar, list flags, integer option);`
This function is an alternative version that checks multiple flags at once, provided as a list of strings.  If the integer option is 0, then it will return TRUE if at least one of the specified flags is present.  If option is 1, then it will return TRUE only if all of the specified flags are present.  If option is 2, it will return the total number of flags that are present.

**Comment by appurist** [comment]
It may not be obvious and could use some documentation but the values like "Cornerstone" etc are from a text column in the users database named `customType`. This field is already available via `DATA_ACCOUNT_TYPE`.  Payment info is `DATA_PAYINFO`, but I believe that's always 0 in InWorldz/Halcyon. Are there any fields remaining that aren't already available?

**Comment by zauberparacelsus** [comment]
Well, the main thing this function intends to address are custom flags that a grid owner might define.  The handling for cornerstone and others with existing LSL access is just for completeness.

**Comment by appurist** [comment]
The examples above (that already exist) aren't flags, they are bits of data stored in fields in the `users` database. At least for the ones normally in `customType`, you can't have more than one value (e.g. in the sense of "Cornerstone" being one of the possible string values, and anything else wouldn't match).

So is this a suggestion to allow a script to set a flag on a user? That would open a lot of questions, such as who gets to set it (land owners? any runtime permissions? user must be on the land too? or in the region?) what if there are competing scripts (one sets, one clears)? 

Is the flag permanent (persists)? Just as long as they are in the region? Or on crossing into other regions, teleport, or on relog?  If it persists, there will need to be a database storage for it, etc.

It's possible to do but there would need to be a lot more detail. A specific list of flags, or if scripter-defined, then at least some of the semantics I mentioned above.  So this isn't a "low-hanging fruit" feature, unless you're only referring to the fields that already exist, and I think most of those are already available. Normally it's not possible for even for the user in question to change them, let alone someone else's script, so there would need to be well-defined rules, and most of the ones you mentioned aren't changeable except by the grid itself.

**Comment by zauberparacelsus** [comment]
`"So is this a suggestion to allow a script to set a flag on a user?"`

No, this is reading, not writing.  Specifically, reading stuff like this...

![untitled](https://user-images.githubusercontent.com/548168/37560684-5010d98a-2a13-11e8-84f7-ad492d5de56b.png)

**Comment by appurist** [comment]
Yeah I realized I had misread your previous reply. Have you seen my edit?

As I said earlier, that text is already available via `DATA_ACCOUNT_TYPE`.

**Comment by appurist** [comment]
Is there anything still missing?

**Comment by kf6kjg** [comment]
Closing at Z's out-of-band request for now.
