### ISSUE TITLE
Next issue with scripts. CHANGED_REGION_START

### ISSUE THREAD

**Issue by WhiteCoreWebUI** [InWorldz/halcyon#433]
Can it be that a region restart is not recognized by LSL i have a script containing this:

  ```
  changed(integer change)
    {
        //Region restartet
        if (change & CHANGED_REGION_START)
        {
            //Request new URL
            llResetScript();
            status = TRUE;
            llRequestURL();
            llInstantMessage(llGetOwner(), "The Region " + llGetRegionName() + " has been restarted, please put me back online!");
        }
    }
```
However if i restart the region i dont get the llInstantMessage it seems like it does not do anything, i would expect to get the message after the restart. 

Edit: nevermind my mistake with llResetScript

**Comment by zauberparacelsus** [comment]
Closing this, was just an extraneous llResetScript() call
