### ISSUE TITLE
Restart Question

### ISSUE THREAD

**Issue by WhiteCoreWebUI** [InWorldz/halcyon#434]
When i restart a region from the console or from the region menu it shuts down, i know in opensim there was a .ini flag to trigger that behaviour or to turn it off, is there something similiar in halcyon?

**Comment by kf6kjg** [comment]
Restarting a region is a task for an external handler. Vinhold's system
currently uses a batch file, Maestro also handles that.

In this way you can manage region status remotely.

**Comment by WhiteCoreWebUI** [comment]
yes but i worry that if a user attempts to restart his/her region via the region tools it wont come back on

**Comment by kf6kjg** [comment]
That's what I was saying, though I had but a phone's keyboard to type upon
then.

A region may also need to be restarted from a crash, again without
intervention from an admin.

For now simply launch your regions via a BAT file that has a loop to
automatically relaunch the region.  You could additionally add logic to
terminate if the exit code from the region so calls for it.  This is the
current method Vinhold uses, though he plans on replacing it with a piece
of .NET code that integrates with his MyWorld grid management platform.

Alternatively you could look into setting up Maestro to do all the above.

**Comment by WhiteCoreWebUI** [comment]
as i dont use myworld (aspx is just not my thing) i reverted to use a free windows program that checks the PID file from halcyon and does a start if the software is down, i might add a code in halcyon itself that does a simple region restart instead of shutting down as right now it takes at least 2 minutes for the region to be back

**Comment by WhiteCoreWebUI** [comment]
for now i can highly recommend https://www.portablefreeware.com/?id=1873 as it allows to add the working directory eliminating the need to pass a argument for the .ini file

**Comment by WhiteCoreWebUI** [comment]
i do all that over PHP :)

**Comment by emperorstarfinder** [comment]
In order for that to happen you would have to actually press Ctrl + C on the region console to completely shut it down.  It is a good safeguard that Halcyon did put in place to ensure region consoles don’t go down by accident.  When a user restarts a region via region tools via the region manager in their region management area on the website or in-world via viewer the regions will restart and be fine.  

 

On our Halcyon test grid we have not yet had trouble with region consoles closing during a region restart.

 

Where your using PHP for your website Maestro probably is the better example of how to implement that in the region.  However Vinhold’s MyWorld Website is pretty good and stable and with that you in fact can create regions and estates via the website administration area and pretty much manage things from the website.  The MyWorld website however is written in aspx/ visual basic.  So your web server would have to support the aspx language.

**Comment by kf6kjg** [comment]
lol, I dislike PHP as much as I dislike ASPX. :P  Alrighty then, you're
call for your grid! :D

**Comment by WhiteCoreWebUI** [comment]
i have myworld installed for the landtool only, but unfortunatly i found to many errors in myworld and my lack of aspx knowledge prevents me from fixing those lol

**Comment by WhiteCoreWebUI** [comment]
but right now i am trying to compile maestro, i hope it works

**Comment by Vinhold** [comment]
WhiteCoreUI: You can always contact me using the MyWorldSrc.com/ContactUs.aspx page for any errors you find. I am actively working on the project and am using it in several world installations as the website front end.

**Comment by WhiteCoreWebUI** [comment]
@Vinhold just tried its impossible: Send Email Failed! Error: Mailbox unavailable. The server response was: Delivery is not allowed to this address.

**Comment by Vinhold** [comment]
Checking on that... Thank you. Last test I did on it was working. Not supposed to foul up without any changes done to it. lol

**Comment by Vinhold** [comment]
ContactUs page is corrected. I had better secured my hMailserver and the page had the wrong email address in it. Ooops.

**Comment by WhiteCoreWebUI** [comment]
ok its out

**Comment by kf6kjg** [comment]
Closing as it's currently the opinion of the developers, as far as I've conversed with them, that restarts should be the responsibility of external monitoring software: such software is needful anyway in case the region spontaneously crashes.
