### ISSUE TITLE
Halcyon.sample.ini causes NullReferenceException crash related to AvatarCurrency

### ISSUE THREAD

**Issue by To-mos** [InWorldz/halcyon#439]
The `Halcyon.sample.ini` file is missing a definition that causes a `NullReferenceException` in `OpenSim.Region.CoreModules.Avatar.Currency.AvatarCurrency.Initialize()` adding `[Economy]` to the `Halcyon.ini` config fixes the issue.

**Comment by appurist** [comment]
Good catch! I'll update the halcyon.sample.ini with an [Economy] section and add some of the definitions that we use here.  e.g. something like:
```
[Economy]
    ; CurrencyServer = "http://localhost/currency.php"
    LandServer = "http://localhost/landtool.php"

    ObjectCapacity = 45000

    ; Money Unit fee to upload textures, animations etc
    PriceUpload = 0

    ; Money Unit fee to create groups
    PriceGroupCreate = 0
```

**Comment by appurist** [comment]
I've added pull request #444 to update the ini file, which doesn't fix the NRE but the sample INI should include this section as well.

**Comment by appurist** [comment]
I've added `EconomyBaseAccount` to the sample INI file in #444.

**Comment by Ana-Green** [comment]
Hi, dear people, my dad did try to figure it out but could find it it is about the last picture or snapshot (a bit off topic) it does not show it on 36 on 37 it did now its just black if you log in again any ideas? 

Further as for the [Economy] section is it possible to add Podex?  https://www.podex.com/

Best  Ana Green 

And thanks to Bob or Vin for everything :)

**Comment by kf6kjg** [comment]
Ana, could you post each problem/idea to their own new issues so devs can see and respond to each properly?  Thanks.
