### ISSUE TITLE
Loading Oar file, terrain settings are not saved to regionsettings table.

### ISSUE THREAD

**Issue by Vinhold** [InWorldz/halcyon#456]
Example case:
In a beta or test grid create a new region. Apply a new land terrain to the region. Put in custom terrain textures and blending settings for it. Make it really stand out different from the default region textures.
Save the region as an oar file.
Load the saved oar file into a production Halcyon grid.
The region will load and the custom textures will apply. You can even see them in the viewer region terrain window all correct. Check the region's regionsettings table record, it will not have any of the texture UUIDs or settings to match. The data is not saved to that record.
Shutdown and restart the region. The terrain textures and blending levels will all be reverted to the defaults seen in the regionsettings table record and the custom ones loaded will all be gone.
It does not matter if the region has any content in it or not. This affects only the terrain textures and blending levels.

**Comment by kf6kjg** [comment]
Try waiting at least 5 minutes before the restart.  Persistence is on a 5 minute interval.  If that allows the reboot to come back up as expected then the problem is one of timing and we can discuss if persistence needs an additional rule for when it is triggered.  If that does not, then there's a bug.

**Comment by Vinhold** [comment]
I have waited several days before restarting the region. The terrain textures and settings are never written to the regionsettings table. When the region is restarted the default settings in the regionsettings table then get applied to the region.

**Comment by Vinhold** [comment]
Update: It finally occurred to me to try changing a terrain setting after loading the oar. That I know forces a data change and save. It did. So now the known workaround is to load an oar file for a region, then edit any one of the terrain elevation entries, save it, then change it back and save it. That will update the regionsettings table and save all the terrain textures and elevations etc. So the primary problem still remains that the same data is not getting put into the regionsettings table when loading the oar.

**Comment by Vinhold** [comment]
Test of Halcyon-0.9.00.158-nnqmhpel-master-dotnet candidate on Avequest correctly recorded region terrain data on loading a test oar, DB regionsettings table checked for changes, passed, then original oar loaded back and checked again, the regionsettings table was again correctly updated. Test passed inspection for saving region terrain data on Oar load. :)
