### ISSUE TITLE
please updat master branch, gettin 1000+ errors..

### ISSUE THREAD

**Issue by Dutchglory** [InWorldz/halcyon#457]
if i build with: 
"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\\msbuild Halcyon.sln"  
getting 7 fails.  (see log file "Halcyon-DOT-NET-build.log-english.txt") 
[Halcyon-DOT-NET-build.log-english.txt](https://github.com/InWorldz/halcyon/files/2152691/Halcyon-DOT-NET-build.log-english.txt)

visual studio 2017 log:
[Halcyon-VS2017-build.log.txt](https://github.com/InWorldz/halcyon/files/2152698/Halcyon-VS2017-build.log.txt)

**Comment by appurist** [comment]
We use VS2017 to do the builds. I'm not sure of the status of attempts with `msbuild`.  The problem in your VS2017 log appears to be a missing MySQL lib.  We just recently eliminated the need to run prebuild to rebuild .sln / .vsproj files, but we still have a runprebuild.bat that copies some references in place.  I suspect what's going on here is that you have most of the files needed in the right place and referenced correctly, by not MySQL.  

To do a build, you shouldn't need to do anything other than grab the latest code from `master`, the run `runprebuild.bat` to copy some files in place, then open the Halcyon.sln file and do a build.  There are still lots of warnings, but I just nuked my whole bin folder, restored the missing deleted files from git, ran runprebuild.bat and rebuilt the project and it went cleanly (no errors).

If you weren't aware that `runprebuild.bat` is still used to copy over some files into `bin`, you may have tried manually updating the missing references and not quite gotten everything where it needs it.

**Comment by appurist** [comment]
That's excellent, glad you got it working!

Although the error could be bad, I'm not sure how it is starting and running normally with that error. The code need `MySql.Data`, but it must be finding the MySQL DLL somewhere and perhaps the fact that it's _only_ reporting `MySql` and not `MySql.Data` means there's a stray reference to a DLL with the wrong name that isn't actually needed.  I can't find any reference to MySql (other than MySql.Data) in my build, so you might want to just do a full forced Rebuild or delete some files (like `bin`) and recreate them and run `runprebuild.bat` again and try another fresh build.

You can also search for MySql references in the Solution Explorer. The only references should be to MySql.Data:
![MySql Project References](https://i.gyazo.com/b1c28e9e366cddb11bc86c7f3dc1342f.png)
