### ISSUE TITLE
Last  picture saved  and when the  background turns  black

### ISSUE THREAD

**Issue by Ana-Green** [InWorldz/halcyon#458]
Report: If  I log in on any region then log out and switch the viewer to the Last Location I see the background last made snap perfectly. If  I log in on any region then log out and switch the viewer to Home I see the background last made snap **Black** like it does not look at the given directory if the viewer has set to home. As reference test, I logged in on several other grids like SL then regardless or  I set the viewer to  **Last Location** or  **Home** I always see the last saved picture perfectly. But not with halcyon, in this case, version.38

Extended  that's on  my own grid::  https://www.dreamcastle-entertainment.eu/

Ana Green

**Comment by emperorstarfinder** [comment]
In this case I think I would also provide the viewer and its version number you are seeing this problem on.  I would also try a different viewer to see if you are getting the same problem with another viewer. 

 Also it usually is more helpful to provide as much info as possible such as screenshots of what your seeing and logs if errors show up to help narrow down where the potential problem may be residing.  

I will try to reproduce this on my team's Halcyon Test-bed grid to see if it occurs as well and if so I will pass what I find on to Halcyon devs to hopefully help identify possible problems.

**Comment by Ana-Green** [comment]
Thank you  but I got  it solved in case  this  happens you just reset  your home from world menu
[13:17]   Frank 渡辺   (Franklyn Watanabe): (FS 5.0.11m) Ana - try resetting home from world menu
[13:17] Ana Fergusson υlғнednar (Ana Enderfield): (FS64 5.0.11v os) ok  will  try  that
[13:26] Ana Fergusson υlғнednar (Ana Enderfield): (FS64 5.0.11v os) Frank that did work after I re-created my home point again it was solved thanks a  lot:)
[13:27]   Frank 渡辺   (Franklyn Watanabe): (FS 5.0.11m) °͜°
The target Firestorm was  FS 5014   but FS 5011 did the same but the fix was easy at least now I know this if it would happen again. Thank you emperorstarfinder  

Best  regards,
Ana  Green 

Case closed.
