### ISSUE TITLE
Question: Can connect from a halcyon grid/standalone to another halcyon grid / standalone ? 

### ISSUE THREAD

**Issue by BogusCurry** [InWorldz/halcyon#52]
Hello ;D

I Know that Inworldz is no hypergrid compatible, but can I connect from a halcyon grid/standalone to another halcyon grid / standalone ?

Greetings

Bogus

**Comment by ddaeschler** [comment]
Besides running all the regions under the same grid there isn't yet a cross-grid travel option. We're keeping options open on that.

**Comment by BogusCurry** [comment]
ahh ok .. thanks for the answer ;D
