### ISSUE TITLE
Halcyon.Sample.Ini Voice Section

### ISSUE THREAD

**Issue by Vinhold** [InWorldz/halcyon#69]
The released file does not contain any section for voice support. I wanted to have voice in my grid back when I started my grid project with InWorldz, but had only heard rumors of an options by Vivox to support OpenSim grids with a free voice account. Well, I eventually stumbled on the information. Perhaps this can be included for those who will wish to have voice as I have not found any alternatives that are still in operation.
[VivoxVoice]
    ; NOTE: This requires contacting Vivox and putting in an application with them.
    ; ## Apply for Vivox at http://support.vivox.com/opensim/ for your free account. See listed terms there.
    ; ## When your application is accepted you will be emailed the section settings to place here.
   enabled = false

**Comment by kf6kjg** [comment]
WIP already in my [code docs branch](https://github.com/InWorldz/halcyon/compare/master...kf6kjg:code_docs_1) with even better notes IMHO.

**Comment by kf6kjg** [comment]
Fixed in PR #95
