### ISSUE TITLE
Add memcached support

### ISSUE THREAD

**Issue by ddaeschler** [InWorldz/halcyon#73]
Due to the slowness of some cloud storage solutions, we will be adding memcached support to create a responsive caching cluster for asset gets.

This ticket will track and associate the work involved. Also opened a ticket on the aperture process.

**Comment by kf6kjg** [comment]
I believe the goal here is being targeted by my [WHIP-LRU](https://github.com/kf6kjg/WHIP-LRU) effort and Mike's precanned tooling ideas.

**Comment by kf6kjg** [comment]
Closing for now.  May still be a useful idea in the future.
