### ISSUE TITLE
Halcyon.ini sections missing?

### ISSUE THREAD

**Issue by Vinhold** [InWorldz/halcyon#8]
While converting the settings from the OpenSim.ini to Halcyon.ini I noticed the [Economy] section is missing. That has the price levels for select processes such as PriceUpload, PriceGroupCreate, 
EconomyBaseAccount. All these are used to control who has access to these features as long as they have the specified level of money, lacking any other way to manage who has the option to use those features.
Also the section for [VivoxVoice] or stub for any other voice connection was missing.
The Current file has all of the IP addreses and Database logon info for InWorldz in it. Not to good for internal security I suspect. Possible replacement with pattern tags?
While some other tags were missing they seemed to be out of date or unused legacy options no longer needed.

**Comment by QuillLittlefeather** [comment]
how do you set this up? can it run in grid mode or can you connect it to a opensim grid?

**Comment by zauberparacelsus** [comment]
No, it cannot connect to an opensim grid.  InWorldz has diverged heavily from opensim, and much of the code, storage formats, and protocols are no longer compatible.

**Comment by ddaeschler** [comment]
The information in the sample ini file isn't from inworldz internal IPs or hosts. That is from my development environment hence the blank passwords.

The economy section that was in the sample file was all defaults and I removed it to simplify the initial setup. So you'll have to add that section back in if you're using it. There will be more documentation and setup information provided soon. This is just the beginning as we just got the code up. Give us a couple of weeks to get more tools and samples out.

**Comment by Vinhold** [comment]
Lol! No problem. Just was setting up a test region to see if I could resolve the trash not being removed in my world. I did find out that it was only related to the folders not getting removed with the "Empty Trash" process however for items the "purge Item" process worked just fine. So the progress continues! I will place the [Economy] parts into my ini file and look for the next step.

**Comment by Vinhold** [comment]
Hi Quill, This is all squeeky new release and significant revision. As ddaeschler says, the rest of the parts are on the way that will get it up and running. It has its own grid mode but won't run with the OpenSim worlds as Zauber explained.

**Comment by QuillLittlefeather** [comment]
Awesome my computer is itching to set this up to try it out. Can't wait for
instructions lol. Thank you for sharing this this is a good move.

**Comment by ddaeschler** [comment]
Going to close this for now.
